# Generated by Django 4.2.5 on 2023-09-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
